model_name: ae_separate
encoder: hierachicalencoder
encoderblock: AtlasReg
decoder: decoderhierarchyv4

output_smoothing_fct: 60
mse_weight: 0.5
coefficient: 0.01

loss_coeff:
  ae_loss: 1.0
  hit_loss: 1.0
  entropy: 0.1