_wandb:
    value:
        cli_version: 0.20.1
        code_path: code/scripts/run.py
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 50
                - 105
            "2":
                - 1
                - 50
                - 105
            "3":
                - 16
                - 55
            "4": 3.12.3
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
data:
    value:
        batch_size_test: 1024
        batch_size_tr: 128
        batch_size_val: 1024
        frac_train_dataset: 0.8
        frac_val_dataset: 0.1
        num_workers: 8
        path: /fast_scratch_1/caloqvae/data/atlas_regular_cat/dataset_eta_030_positive_cat_smeared.hdf5
        phi: 14
        r: 24
        z: 7
debug:
    value: 0
device:
    value: gpu
engine:
    value:
        learning_rate: 0.0001
        n_epochs: 250
freeze_vae:
    value: 1
gpu_list:
    value:
        - 2
load_state:
    value: 0
model:
    value:
        coefficient: 0.01
        decoder: decoder
        encoder: hierachicalencoder
        encoderblock: AtlasReg
        latent_hierarchy_lvls: 4
        latent_nodes: 302
        model_name: autoencoderbase
        mse_weight: 0.5
        output_smoothing_fct: 60
run_path:
    value: /home/javier/Projects/CaloQVAE/outputs/2025-06-11/20-46-13/wandb/run-20250611_204614-4f745nwj/files/AtlasConditionalQVAE3DHD_atlas_default_190.pth
save_hists:
    value: 1
save_partition:
    value: 1
save_state:
    value: 1
task:
    value:
        - train
        - validate
        - test
wandb:
    value:
        entity: caloqvae
        project: caloqvae
        watch: 0
wandb_enabled:
    value: 1
