save_state: 1
load_state: 0
save_hists: 1
save_partition: 1
freeze_vae: 1

run_path: ""
# config_path: "/fast_scratch_1/caloqvae/jtoledo/wandb/run-20250712_153312-7p5kb9zm/files/ae_separate_230_config.yaml"
config_path: "/fast_scratch_1/caloqvae/lzhu/wandb/run-20250718_163200-em9a1ujl/files/ae_separate_best_config.yaml"

device: gpu
gpu_list:
  - 5

defaults:
  - data: AtlasReg020
  - wandb: ML2
  - model: model8_geo_decoder
  - engine: engine1
  - rbm: zephyr
  - _self_

n_epochs: 350
epoch_freeze: 200
epoch_start: 0