#!/usr/bin/env python3
"""Extract the Sim2Science figure environments for a figure-only build.

The manuscript keeps figures and captions in the normal section sources.  This
small extractor copies only top-level ``figure``, ``figure*``, and
``wrapfigure`` environments into a generated TeX fragment, so the standalone
figure PDF cannot silently drift from the paper captions.  The
``qpu_method_figure.tex`` input is expanded at the point where the appendix
includes it.

The generated fragment is an intermediate build artifact; it is intentionally
written under ``paper/Sim2Science_Workshop/build`` by the Makefile.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
PAPER_DIR = ROOT / "paper" / "Sim2Science_Workshop"

SOURCE_FILES = (
    PAPER_DIR / "sections" / "introduction.tex",
    PAPER_DIR / "sections" / "method.tex",
    PAPER_DIR / "sections" / "experiments.tex",
    PAPER_DIR / "sections" / "appendix.tex",
)

ENVIRONMENT_TOKEN = re.compile(
    r"\\(?P<action>begin|end)\{(?P<name>[A-Za-z*]+)\}"
)
INPUT_TOKEN = re.compile(r"\\input\s*\{(?P<path>[^}]+)\}")
FIGURE_ENVIRONMENTS = {"figure", "figure*", "wrapfigure"}


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Path for the generated TeX figure fragment.",
    )
    return parser.parse_args()


def _resolve_input(source: Path, input_name: str) -> Path | None:
    """Resolve a local TeX input without following external paths."""

    candidate = Path(input_name.strip())
    if candidate.suffix != ".tex":
        candidate = candidate.with_suffix(".tex")
    # TeX resolves the appendix's ``qpu_method_figure.tex`` from the paper
    # working directory, while section-local inputs would be relative to the
    # section.  Try both locations to mirror that behavior.
    candidates = (source.parent / candidate, PAPER_DIR / candidate)
    for possible in candidates:
        resolved = possible.resolve()
        try:
            resolved.relative_to(PAPER_DIR.resolve())
        except ValueError:
            continue
        if resolved.is_file():
            return resolved
    return None


def _extract_environment(text: str, start: int, source: Path) -> tuple[str, int]:
    """Return one complete environment and the offset immediately after it."""

    opening = ENVIRONMENT_TOKEN.match(text, start)
    if opening is None or opening.group("action") != "begin":
        raise ValueError(f"Expected an environment opening in {source}:{start}")

    stack = [opening.group("name")]
    cursor = opening.end()
    while stack:
        token = ENVIRONMENT_TOKEN.search(text, cursor)
        if token is None:
            raise ValueError(
                f"Unclosed {stack[0]!r} environment while reading {source}"
            )

        name = token.group("name")
        if token.group("action") == "begin":
            stack.append(name)
        elif name != stack[-1]:
            raise ValueError(
                f"Mismatched environment {name!r} in {source}"
            )
        else:
            stack.pop()
        cursor = token.end()

    return text[start:cursor], cursor


def _extract_file(source: Path, active: set[Path]) -> list[str]:
    """Extract figures from one source, expanding local ``\\input`` files."""

    source = source.resolve()
    if source in active:
        raise ValueError(f"Recursive TeX input while reading {source}")

    active = {*active, source}
    text = source.read_text()
    figures: list[str] = []
    cursor = 0

    while cursor < len(text):
        environment = ENVIRONMENT_TOKEN.search(text, cursor)
        tex_input = INPUT_TOKEN.search(text, cursor)

        if tex_input is not None and (
            environment is None or tex_input.start() < environment.start()
        ):
            input_path = _resolve_input(source, tex_input.group("path"))
            if input_path is not None:
                figures.extend(_extract_file(input_path, active))
            cursor = tex_input.end()
            continue

        if environment is None:
            break

        if (
            environment.group("action") == "begin"
            and environment.group("name") in FIGURE_ENVIRONMENTS
        ):
            figure, cursor = _extract_environment(text, environment.start(), source)
            figures.append(figure)
        else:
            cursor = environment.end()

    return figures


def build_figure_fragment() -> str:
    """Build the shared figure-only TeX body in manuscript order."""

    parts = [
        "% Generated by scripts/extract_sim2science_figures.py; do not edit.\n",
        "% Figure environments and captions remain sourced from the manuscript.\n",
    ]

    for source in SOURCE_FILES:
        if source.name == "appendix.tex":
            # Match the manuscript's appendix numbering without importing its
            # prose, tables, or subsection headings.
            parts.extend(
                (
                    "\n\\clearpage\n",
                    "% Keep the paper's appendix figure numbering in the catalog.\n",
                    "\\setcounter{figure}{0}\n",
                    "\\renewcommand{\\thefigure}{A.\\arabic{figure}}\n",
                    "\\renewcommand{\\theHfigure}{app.\\arabic{figure}}\n",
                )
            )
        parts.append(f"\n% Source: {source.relative_to(PAPER_DIR)}\n")
        parts.extend(figure + "\n\\clearpage\n" for figure in _extract_file(source, set()))

    return "".join(parts)


def main() -> None:
    args = _parse_args()
    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(build_figure_fragment())
    print(f"[figures-only] Wrote {output}")


if __name__ == "__main__":
    main()
